{
    "error_message": "One of the dimensions in the output is <= 0 due to downsampling in conv2d_5. Consider increasing the input size. Received input shape [None, 249, 1, 64] which would produce output shape with a zero or negative value in a dimension.",
    "traceback": "Traceback (most recent call last):\n  File \"/Users/pier/Projects/neural_networks/src/main.py\", line 91, in process_configuration\n    neural_network = NeuralNetwork(\n                     ^^^^^^^^^^^^^^\n  File \"/Users/pier/Projects/neural_networks/src/deepnn/model.py\", line 37, in __init__\n    self.model = self._build_model()\n                 ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/pier/Projects/neural_networks/src/deepnn/model.py\", line 72, in _build_model\n    prev_layer = tf.keras.layers.Conv2D(\n                 ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/pier/Projects/neural_networks/.venv/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"/Users/pier/Projects/neural_networks/.venv/lib/python3.11/site-packages/keras/src/layers/convolutional/base_conv.py\", line 354, in compute_output_shape\n    raise ValueError(\nValueError: One of the dimensions in the output is <= 0 due to downsampling in conv2d_5. Consider increasing the input size. Received input shape [None, 249, 1, 64] which would produce output shape with a zero or negative value in a dimension.\n"
}